version: "3"
services:

  monolithic_service:
    build: ./Solutions/Monolithic
    container_name: monolithic_service
    ports:
      - "5001:5000"
    env_file:
      - .env

  locust:
    build: ./locust
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=http://localhost:5001
    volumes:
      - ./locust:/mnt/locust
    depends_on:
      - monolithic_service 