version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5

  api_service:
    build: ./Solutions/Distributed/api_service
    container_name: api_service
    ports:
      - "5001:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_service:
    build: ./Solutions/Distributed/filter_service
    container_name: filter_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  screaming_service:
    build: ./Solutions/Distributed/screaming_service
    container_name: screaming_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  publish_service:
    build: ./Solutions/Distributed/publish_service
    container_name: publish_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  locust:
    build: ./locust
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=http://api_service:5000
    volumes:
      - ./locust:/mnt/locust
    depends_on:
      - api_service
